apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: askbias-sqlite-pvc
  labels:
    app: mever-askbias
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: pve-local-lvmthin-ext4
