apiVersion: v1
kind: Service
metadata:
  name: mever-askbias
  labels:
    app: mever-askbias
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: mever-askbias
